# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-14 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commondity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CommodityName', models.CharField(max_length=100)),
                ('CommodityCategory', models.CharField(blank=True, max_length=50)),
                ('CommodityPrice', models.DecimalField(decimal_places=2, max_digits=6)),
                ('CommodityDateTime', models.DateTimeField(auto_now_add=True)),
                ('CommodityContent', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-CommodityDateTime'],
            },
        ),
    ]
