# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-14 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commondity',
            name='CommondityImage',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder／'),
        ),
    ]
