# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-14 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0002_commondity_commondityimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commondity',
            name='CommodityPrice',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
    ]
