# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-19 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0004_auto_20170514_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commondity',
            name='CommodityCategory',
            field=models.CharField(blank=True, max_length=50, verbose_name='商品类别'),
        ),
        migrations.AlterField(
            model_name='commondity',
            name='CommodityContent',
            field=models.TextField(blank=True, null=True, verbose_name='商品说明'),
        ),
        migrations.AlterField(
            model_name='commondity',
            name='CommodityDateTime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发布日期'),
        ),
        migrations.AlterField(
            model_name='commondity',
            name='CommodityName',
            field=models.CharField(max_length=100, verbose_name='商品名称'),
        ),
        migrations.AlterField(
            model_name='commondity',
            name='CommodityPrice',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='商品价格'),
        ),
        migrations.AlterField(
            model_name='commondity',
            name='CommondityImage',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder', verbose_name='商品图片'),
        ),
    ]
