# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-20 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0005_auto_20170519_0510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commondity',
            options={'ordering': ['-CommodityDateTime'], 'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
        migrations.AddField(
            model_name='commondity',
            name='Mobile',
            field=models.CharField(blank=True, max_length=11, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='commondity',
            name='CommodityDateTime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='登记日期'),
        ),
        migrations.AlterField(
            model_name='commondity',
            name='CommondityImage',
            field=models.ImageField(default='static/upload/None/no-img.jpg', upload_to='static/upload', verbose_name='商品图片'),
        ),
    ]
