# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-22 20:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0005_auto_20170521_1627'),
        ('commodity', '0006_auto_20170520_0950'),
    ]

    operations = [
    ]
